baseURL = "https://qubiit.github.io/"
languageCode = "en-us"
title = "Qu-bit's blog"
theme = "PaperMod"
#sectionPagesMenu = "main"

disableThemeToggle = "true"
ShowReadingTime = "true"
ShowToc = "true"
TocOpen = "true"

[taxonomies]
   tag = "tags"
   category = "categories"


[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blog/"
    weight = 10
	
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10



[Params]
    env = "production"
    defaultTheme = "dark"
    ShowReadingTime = "true"
    ShowShareButtons = "true"
    ShowBreadCrumbs = "true"
    [cover]
        linkFullImages = "true"
    [profileMode]
        enabled = true
        title = "<Title>"
        subtitle = "This is subtitle"
        imageUrl = "<image link>"
        imageTitle = "<title of image as alt>"
        imageWidth = 120
        imageHeight = 120
