baseURL: https://qubiit.github.io/
languageCode: en-us
title: QuBit
theme: PaperMod
sectionPagesMenu: main


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
# ignoreFiles: 
#   - "/static/admin/.*"

ignoreFiles: 
  - "/content/writings/.*"
  - "/content/notes/.*"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # title: Qu-bit's blog #have it on global
  description: QuBit's blog
  keywords: [Blog, Portfolio, Qu-bit]
  author: QuBit
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/favicon/apple-touch-icon.png"

  label:
    text: "QuBit's Blog"
    icon: "/favicon/android-chrome-512x512.png"
    iconHeight: 50

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: QuBit
    subtitle: Data Scientist | ML Engineer
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: Blog
        url: blog
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: https://github.com/qubiit
    - name: gitlab
      url: https://gitlab.com/qu-bit
    # - name: kaggle
    #   url: https://www.kaggle.com/qubiit
    - name: email
      url: contact

  analytics:
    google:
      SiteVerificationTag: "82c872f87d5b4b018a3b7cbc85afc9a1"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: Categories
    #   title: Categories
    #   url: /categories/
    #   weight: 20
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 30
    - identifier: blog
      name: Blog
      title: Blog
      url: /blog/
      weight: 10
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai


privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true



